### ISSUE TITLE
Choose the Free Rate-Limited Developer Plan or Use Your Own OpenAI Key

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#103]
After signing up, I have two choices: either use my own OpenAI API key or proceed with the free rate-limited developer plan.

## Tasks

- [ ] Ability to use my own OpenAI API key
- [ ] Free Rate-Limited Developer Plan
  - [ ] **Rate Limiting:** Implement rate limits on the daily number of tokens a user can consume.
  - [ ] Implement proxy APIs for LLM Embedding and LLM Inference.
