### ISSUE TITLE
Sirji should be able to write new functional test cases for a specified functionality

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#143]
## Sample problem statement:
- Write functional test cases for a specified API using the framework and conventions of the already written test cases.
- Implement a given Node JS API and write a functional test case in a single run.

## Tasks
- [x] New agent for writing the test cases
- [x] Agent should write negative test cases too
- [x] For writing test cases, rely on the code implemented in the repository. Do not rely on OpenAPI specs and other documentation files.
