### ISSUE TITLE
PyPI package for Sirji messaging protocol implementation to create, validate and parse messages.

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#16]
## The problem to solve

To make the Sirji message protocol reusable between different user interfaces like GUI, VS Code extension, this issue aims at publishing the Sirji message protocol as a package.

## Tasks
- [x] Message parsing functionality for converting a string message to a message object.
- [x] Permissions matrix to store the allowed actions from one agent to another.
- [x] Message classes based on actions
- [x] Factory over the message classes
- [x] Custom exceptions to be exposed
- [x] System prompt generation and factory over it
- [x] Enums for actions and agents to avoid hardcodings
- [x] Ability to send messages for READ_DIR and READ_FILE
- [x] Test cases with a threshold of 80% coverage
- [x] README with usages
- [x] Publish to PyPI
- [x] Integrate with VS Code Extension
