### ISSUE TITLE
PyPI package for Crawler and search tools used by Sirji.

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#18]
## The problem to solve
To make the Sirji tools (crawler, search, and logger) reusable between different user interfaces like GUI, VS Code extension, this issue aims at publishing them as a package.

## Tasks
- [x] Crawler tool to download as markdown
- [x] Search tool to fetch search results for a term
- [x] Logger tool to implement the custom logger
- [x] Test cases with threshold of 80% coverage
- [x] README with usages
- [x] Publish to PyPI
- [x] Search using the search page parse
- [x] Integrate with VS Code extension
