### ISSUE TITLE
PyPI package for Research, Coding and Planning agents used by Sirji.

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#19]
## The problem to solve
To make the Sirji message handling via agents (planner, coder, and researcher) reusable between different user interfaces like GUI, VS Code extension, this issue aims at publishing them as a package.

## Tasks
- [x] Researcher to work with the existing assistant if the assistant ID is passed to it
- [x] Researcher to be integrated with Crawler, Search and Logger tools from sirji-tools package
- [x] Researcher to implement the train and infer functionality
- [x] Researcher to handle different messages based on action
- [x] Coder to take in the history of messages as input and stop relying on history from memory
- [x] Base class for both Coder and Planner
- [x] Planner to take in the history of messages as input and stop relying on history from memory
- [x] README with usages
- [x] Publish to PyPI
