### ISSUE TITLE
Show the running total for tokens consumed and dollar cost

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#22]
To get an idea of the dollar cost for each run, show the running total of tokens consumed and the running dollar cost.

## Tasks
- [x] From sirji-agents, return the tokens consumed (prompt and completion) in the single message processing.
- [x] Persist the running total in Coder, Planner and Researcher conversations files.
- [x] Show total tokens consumed and dollar amount at their respective places on the chat window.
