### ISSUE TITLE
Integrate PyPI packages with Dogfood GUI

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#23]
## The problem to solve

To test that everything which is needed for Sirji UI to work is available in the PyPI packages, we will integrate them with the Dogfood GUI version.

## Tasks:
- [ ] Integrate sirji-messages with GUI
- [ ] Integrate sirji-agents with GUI
- [ ] Persisting conversation history
- [ ] Test end to end with different problem statements
