### ISSUE TITLE
README design for the VS Code Release

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#29]
## The problem to solve

Write a README mentioning the architecture, necessary details for using the extension, etc.

## Tasks
- [x] Architecture Diagram
- [x] Setup steps for collaborators
- [x] Installation
- [x] Demo videos section
- [x] Where to report issues?
- [x] Office hours section
- [x] How can someone contribute?
