### ISSUE TITLE
Simplified Package Installation with Pre-Check

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#33]
## Description

Presently Sirji installs packages at the machine level which can interfere with machine-level installed versions. We need to avoid this as much as possible.

## Tasks
- [x] For programming language-specific packages that can be installed locally, Siji should proceed to install them directly without prompting for confirmation.
- [x] For other installations, that do not fit the above, Sirji should ask for confirmation.
- [x] Additionally, before initiating the installation process, the system will first verify if the package is already installed by checking its version.
