### ISSUE TITLE
Continuous Running Process Management

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#35]
## Description

Special handling for continuously running processes (for example, Server process).

## Tasks
- [x] Introduce new message action RUN_SERVER for commands which will start a continuously running process.
- [x] System prompt changes to enable messages with the new action. 
- [x] `vscode.Task` is to be used for starting such processes.
